ticketing/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'ticketing'
urlpatterns = [
    path('', views.page_index, name='index'),

    path('redeem/', views.page_redeem, name='redeem'),
    path('redeemed/', views.page_redeem_done, name='redeemed'),

    path('stats/', views.page_stats, name='stats'),
    path('timetables/', views.form_timetables, name='timetables'),
    path('timetables/success', views.page_timetables_loaded, name='timetables_done'),

    path('codes/<int:pk>', views.file_codepdf, name='codepdf'),
    path('tickets/<int:pk>', views.page_tickets, name='tickets'),
    path('tickets/<int:pk>/<str:group_id>/<int:part>', views.file_delivery_group, name='delivery_group'),

    path('api/redeem/', views.ApiRedeem.as_view(), name='api_redeem'),
    path('api/validate_code/', views.ApiRedeem.as_view(), name='api_validate_code'),
    path('api/print/', views.ApiPrintTicket.as_view(), name='api_print'),
    path('api/count', views.ApiCount.as_view(), name='api_count'),
    path('api/graph', views.ApiGraph.as_view(), name='api_graph'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vdaywebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ticketing.urls')),
    path('admin/', admin.site.urls)
]

ticketing/forms.py
from django import forms


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class CSVFileForm(forms.Form):
    files = MultipleFileField()

ticketing/views.py
from django.http import HttpResponseRedirect, FileResponse
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAdminUser
from rest_framework.request import Request
from rest_framework.response import Response
from vdaywebsite.settings import CONTACT_EMAIL, NUM_TICKETS_PER_PDF
from .models import Ticket, TicketCode, SortTicketsRequest
from .forms import CSVFileForm
from .input_validation import is_code_exists, is_code_unconsumed, is_recipient_exists
from .constants import DirectoryLocations, FileNames, STUDENTS, TEMPLATES, STUDENTS_LIST, FONTS
from .ticket_printer import TicketsToPDF
from .timetable_parser import get_student_classes
import os
import re
import csv
import json
import datetime
from io import StringIO


def page_index(request):
    return HttpResponseRedirect(reverse('ticketing:redeem'))


@staff_member_required
def form_timetables(request):
    if request.method == 'POST':
        form = CSVFileForm(request.POST, request.FILES)
        if form.is_valid():
            files = [csv.reader(StringIO(file.read().decode())) for file in request.FILES.getlist('files')]
            with open(FileNames.PEOPLE, 'w') as file:
                students = get_student_classes(files)
                writer = csv.DictWriter(file, fieldnames=['ID', 'Name', 'First Name', 'Last Name', 'ARC',
                                                          'P1', 'P2', 'P3', 'P4'])
                writer.writeheader()
                writer.writerows(students)

            for file in request.FILES.getlist('files'):
                print(file)
                with open(f"{DirectoryLocations.TIMETABLES_INPUT}/{file}", 'wb') as csv_file:
                    for chunk in file.chunks():
                        csv_file.write(chunk)
            return HttpResponseRedirect(reverse("ticketing:timetables_done"))
    else:
        form = CSVFileForm()
    return render(request, 'ticketing/timetables.html', {'form': form})


@staff_member_required
def page_timetables_loaded(request):
    return render(request, 'ticketing/timetables_done.html')


@staff_member_required
def page_stats(request):
    return render(request, 'ticketing/stats.html')


class ApiCount(APIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAdminUser]

    @staticmethod
    def get(request: Request):
        data = {}

        # For each item type in a ticket
        for choice in Ticket.item_type.field.choices:
            item_type = choice[0]
            item_type_name = item_type.lower().replace(' ', '_')

            # Get total ticket codes created
            created = TicketCode.objects.filter(item_type=item_type).count()
            data[f'{item_type_name}s_created'] = created

            # Gets total redeemed ticket codes
            # (actually the number of tickets, in case some were manually added)
            redeemed = Ticket.objects.filter(item_type=item_type).count()
            data[f'{item_type_name}s_redeemed'] = redeemed

        # Initialise grades to zero
        for grade in range(7, 13):
            data[f"grade_{grade}"] = 0

        # Get number of tickers per grade
        for ticket in Ticket.objects.all():
            recipient_arc = STUDENTS[ticket.recipient_id]['ARC']
            recipient_grade = re.match(r"\d+", recipient_arc)

            if recipient_grade is not None and f"grade_{recipient_grade[0]}" in data:
                data[f"grade_{recipient_grade[0]}"] += 1
            else:
                print(f"Stats: Error getting grade of {STUDENTS[ticket.recipient_id]}")

        return Response(data=data, status=status.HTTP_200_OK)


class ApiGraph(APIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAdminUser]

    @staticmethod
    def get(request: Request, *args, **kwargs):
        """
        Returns a histogram with time in the x-axis (in hourly intervals)
        and number of tickets redeemed in y-axis
        """
        # Not enough tickets to make a useful graph
        if Ticket.objects.count() <= 2:
            return Response(data={"success": "false"}, status=status.HTTP_200_OK)

        oldest_redeem = Ticket.objects.earliest('date').date + datetime.timedelta(hours=10)     # add 10 hours for timezone
        newest_redeem = Ticket.objects.latest('date').date + datetime.timedelta(hours=10)

        times = []  # x-axis
        num_tickets = []    # y-axis
        while oldest_redeem < newest_redeem:
            times.append(oldest_redeem.replace(microsecond=0, second=0, minute=0).strftime("%Y-%m-%d %H:%M:%S"))
            num_tickets.append(Ticket.objects.filter(date__date=oldest_redeem.date(), date__hour=oldest_redeem.hour).count())
            oldest_redeem += datetime.timedelta(hours=1)

        return Response(
            data={"success": "true", "xData": times, "yData": num_tickets},
            status=status.HTTP_200_OK
        )


@staff_member_required
def file_codepdf(request, pk):
    return FileResponse(open(f'{DirectoryLocations.GENERATED_TICKET_CODES}/{pk}.pdf', 'rb'))


@staff_member_required
def page_tickets(request, pk):
    sort_tickets_request = SortTicketsRequest.objects.get(pk=pk)
    group_data = {}
    for group in sort_tickets_request.deliverygroup_set.all():
        group_data[group.code] = {}
        group_data[group.code]["num_tickets"] = group.tickets.count()
        group_data[group.code]["parts"] = group.parts_printed

    return render(request, 'ticketing/tickets.html', {
        'pk': pk,
        'num_tickets_per_pdf': NUM_TICKETS_PER_PDF,
        'date': sort_tickets_request.date,
        'group_data': json.dumps(group_data)
    })


@staff_member_required
def file_delivery_group(request, pk, group_id, part):
    return FileResponse(open(f'{DirectoryLocations.SORTED_TICKETS}/{pk}/{group_id}_{part}.pdf', 'rb'))


def page_redeem_done(request):
    return render(request, 'ticketing/redeemed.html')


def page_redeem(request):
    templates = TEMPLATES
    students = STUDENTS_LIST
    return render(request, 'ticketing/redeem.html', {'templates': templates, 'students': students,
                                                     'contact_email': CONTACT_EMAIL, 'fonts': FONTS})


class ApiRedeem(APIView):
    @staticmethod
    def get(request: Request):
        """
        Endpoint for users to check if a code is valid
        """
        code = request.query_params.get('inputted_code').upper()

        # If the code exists, get what item it is. if it doesn't leave it blank
        data = {
            'is_exists': is_code_exists(code),
            'is_unconsumed': is_code_unconsumed(code),
            'item_type': TicketCode.objects.get(code=code).item_type if is_code_exists(code) else ""
        }

        return Response(data=data, status=status.HTTP_200_OK)

    @staticmethod
    def post(request: Request):
        """
        Endpoint for users to redeem a ticket
        """
        data = request.data

        # Validate code
        if is_code_exists(data['code']):
            ticket_code = TicketCode.objects.get(code=data['code'])
        else:
            return Response(data={"success": "false", "error": "This is not a valid code."},
                            status=status.HTTP_200_OK)

        if not is_code_unconsumed(data['code']):
            return Response(data={"success": "false", "error": "This code has already been used."},
                            status=status.HTTP_200_OK)

        # Validate recipient
        if not is_recipient_exists(data['recipient_id']):
            return Response(data={"success": "false", "error": "This recipient does not exist."},
                            status=status.HTTP_200_OK)

        # Create the ticket
        ticket = Ticket(
            recipient_id=data['recipient_id'],
            item_type=ticket_code.item_type,
            is_handwritten=(data['is_handwritten'] == "True"),
            template=data['template'],
            code=ticket_code,
        )
        if ticket.item_type == "Special Serenade":
            ticket.ss_period = data['period']
        ticket.save()

        # Create the ticket file
        with open(f'{DirectoryLocations.REDEEMED_TICKETS}/{ticket.pk}.svg', 'wb') as file:
            file.write(bytes(data['message'], 'utf-8'))

        # Mark the ticket code as consumed
        ticket_code.is_unconsumed = False
        ticket_code.save()

        # Redirect to the purchased screen
        return Response(data={"success": "true"}, status=status.HTTP_200_OK)


class ApiPrintTicket(APIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAdminUser]

    @staticmethod
    def post(request: Request):
        pk = request.data['pk']
        group_code = request.data['group']
        part = int(request.data['part'])
        padding = int(request.data['padding'])
        enforce_boundaries = request.data['boundary'] == "true"

        group = SortTicketsRequest.objects.get(pk=pk).deliverygroup_set.get(code=group_code)

        if not os.path.exists(f"{DirectoryLocations().SORTED_TICKETS}/{pk}"):
            os.mkdir(f"{DirectoryLocations().SORTED_TICKETS}/{pk}")

        TicketsToPDF(group.tickets.all()[(part - 1) * NUM_TICKETS_PER_PDF:
                                         min(part * NUM_TICKETS_PER_PDF, group.tickets.count())],
                     f"{DirectoryLocations().SORTED_TICKETS}/{pk}/{group_code}_{part}.pdf",
                     group_code,
                     starting_index=(part - 1) * NUM_TICKETS_PER_PDF,
                     padding=padding,
                     enforce_boundaries=enforce_boundaries)

        group.parts_printed.append(part)
        group.save()

ticketing/templates/ticketing/purchased.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Redeemed!</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/redeemed.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icons/done.svg' %}"/>
</head>
<body>
    <div id="content">
        <h1 style="text-align: center">Your ticket has been successfully redeemed!</h1>
        <br>
        <div class="centre">
            <span class="img" title="Redeem Another" id="repeat" onclick="location.href={% url 'ticketing:purchase' %}"></span>
            <p>Redeem Another</p>
        </div>
    </div>
</body>
</html>

ticketing/templates/ticketing/redeem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redeem Ticket</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/choices.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/signature_pad.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/redeem.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icons/heart.png' %}"/>
    <script src="https://cdn.jsdelivr.net/npm/choices.js@9.0.1/public/assets/scripts/choices.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/signature_pad@4.1.4/dist/signature_pad.umd.min.js" integrity="sha256-9WcA0fSt3eVJuMgyitGmuRK/c86bZezvLcAcVMWW42s=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fabric@5.3.0-browser/dist/fabric.min.js" integrity="sha256-SPjwkVvrUS/H/htIwO6wdd0IA8eQ79/XXNAH+cPuoso=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fontfaceobserver@2.3.0/fontfaceobserver.standalone.min.js"></script>
</head>
<body>
    <div id="content">
        <h1>Redeem Your Ticket</h1>
        <div class="input">
            <h3>Code</h3>
            <p class="info">A string of 10 random letters. You buy this in person from the prefects.</p>
            <input type="text" title="Ticket Code" maxlength="10" minlength="10" required id="code">
            <p hidden class="info error" id="codeError"></p>
        </div>
        <div hidden class="input" id="periodForm">
            <h3>Period</h3>
            <p class="info">Please select which period you would like the Special Serenade to happen in.</p>
            <select id="period">
              <option value="-">-</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
            <p hidden class="info error" id="periodError">*Required</p>
        </div>
        <div class="input">
            <h3>Recipient</h3>
            <select title="Select Recipient" id="recipient"></select>
            <p hidden class="info error" id="recipientError">*Required</p>
        </div>
        <div class="input">
            <h3>Handwrite or Type?</h3>
            <select title="Choose whether handwritten or typed" id="is_handwritten">
              <option value="True">Handwrite</option>
              <option value="False">Type</option>
            </select>
        </div>
        <div hidden class="input" id="formTyped">
            <div class="input">
                <h3>Template</h3>
                <select title="Typed Template" id="typed_template">
                    <option value="Blank" selected>Blank</option>
                </select>
            </div>
            <div class="input">
                <h3>Font</h3>
                <select title="Font" id="font_selector"></select>
            </div>
            <div class="input">
                <h3>Message</h3>
                <p class="info">Create/edit/delete text boxes to write your message.</p>
                <canvas id="fabric" width="600" height="356" style="border: 1px solid black"></canvas>
            </div>
            <div class="buttons typed">
                <span class="img add" id="fabric_add"></span>
                <span class="img undo" id="fabric_undo"></span>
                <span class="buttonDivider"></span>
                <span class="img reset" id="fabric_reset"></span>
                <span class="img clear" id="fabric_clear"></span>
            </div>
            <p hidden class="info error" id="tooManyTextBoxesError">*Chill with the text boxes! Hint: each text box can contain multiple lines.</p>
            <p hidden class="info error" id="weirdCharactersError">*Emojis and some special characters will not show correctly when printing.</p>
            <p hidden class="info error" id="overFlowingError">*Some parts of your message (or a textbox) may be outside the box or too close to the edge.</p>
            <p hidden class="info error" id="typedError">*Your message is blank!</p>
        </div>
        <div class="input" id="formHandwriting">
            <div class="input">
                <h3>Template</h3>
                <select title="Handwriting Template" id="handwriting_template">
                  <option value="Blank" selected>Blank</option>
                </select>
            </div>
            <div class="input no_select">
                <h3>Message</h3>
                <p class="info">Handwrite a message!</p>
                <canvas id="signature_pad"></canvas>
                <p hidden class="info error" id="handwritingError">*Required</p>
                <div class="buttons">
                    <span class="img undo" id="signature_pad_undo"></span>
                    <span class="buttonDivider"></span>
                    <span class="img clear" id="signature_pad_clear"></span>
                </div>
            </div>
        </div>
        <p hidden id="errors" style="color: red"></p>
        <div class="centre" style="padding-top:20px">
            <span class="img" title="Redeem" id="redeem"></span>
            <p>Redeem Ticket</p>
        </div>
    </div>
</body>
<script>
    const csrf_token = "{{csrf_token}}";
    const students = {{students|safe}};
    const templates = {{templates|safe}};
    const fonts = {{fonts|safe}};
    const redeemed_url = "{% url 'ticketing:redeemed' %}";
    const validate_code_url = "{% url 'ticketing:api_validate_code' %}";
    const redeem_api_path = "{% url 'ticketing:api_redeem' %}";
    const static_path = "{% static '' %}";
    const contact_email = "{{contact_email}}";
</script>
    <script type="text/javascript" src="{% static 'js/redeem.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/signature_pad.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/fabric.js' %}"></script>
</html>

ticketing/templates/ticketing/redeemed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Redeemed!</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/redeemed.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icons/done.svg' %}"/>
</head>
<body>
    <div id="content">
        <h1 style="text-align: center">Your ticket has been successfully redeemed!</h1>
        <br>
        <div class="centre">
            <span class="img" title="Redeem Another" id="repeat" onclick="location.href={% url 'ticketing:redeem' %}"></span>
            <p>Redeem Another</p>
        </div>
    </div>
</body>
</html>

ticketing/templates/ticketing/sort.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stats & Sort Tickets</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sort.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <link rel="icon" type="image/png" href="{% static 'icons/math.svg' %}"/>
</head>
<body>
<div id="content">
  <div>
     <h1>Stats</h1>
    <table>
      <tr>
        <th>Item</th>
        <th>Number of Created</th>
        <th>Number of Redeemed</th>
      </tr>
      <tr>
        <td>Chocolate</td>
        <td id="chocolates_created"></td>
        <td id="chocolates_redeemed"></td>
      </tr>
      <tr>
        <td>Roses</td>
        <td id="roses_created"></td>
        <td id="roses_redeemed"></td>
      </tr>
      <tr>
        <td>Serenades</td>
        <td id="serenades_created"></td>
        <td id="serenades_redeemed"></td>
      </tr>
      <tr>
        <td>Special Serenades</td>
        <td id="special_serenades_created"></td>
        <td id="special_serenades_redeemed"></td>
      </tr>
       <tr>
        <td><b>Total</b></td>
        <td id="total_created"></td>
        <td id="total_redeemed"></td>
      </tr>
    </table>
    <button id="refresh">Refresh</button>
  </div>
  <br>
  <div>
    <h1>Sort</h1>
    <form method="post"> {% csrf_token %}
      <div class="input">
        <h3>How many serenading groups?</h3>
        {{ form.serenading_groups }}
      </div>
      <div class="input">
        <h3>How many non-serenading groups?</h3>
        {{ form.non_serenading_groups }}
      </div>
    </form>
    <button id="sort">Sort</button>
  </div>
</div>
</body>
<script>
    $('#sort').on('click', () => {
        this.hide();
        setTimeout(() => {
            this.show();
        }, 5000);
    });

    function refresh() {
        $.getJSON('{% url 'ticketing:sort' %}', "count", (data) => {
            $('#chocolates_created')[0].innerText = data.chocolates_created;
            $('#chocolates_redeemed')[0].innerText = data.chocolates_redeemed;
            $('#roses_created')[0].innerText = data.roses_created;
            $('#roses_redeemed')[0].innerText = data.roses_redeemed;
            $('#serenades_created')[0].innerText = data.serenades_created;
            $('#serenades_redeemed')[0].innerText = data.serenades_redeemed;
            $('#special_serenades_created')[0].innerText = data.special_serenades_created;
            $('#special_serenades_redeemed')[0].innerText = data.special_serenades_redeemed;
            $('#total_created')[0].innerHTML = `<b>${data.chocolates_created + data.roses_created + data.serenades_created + data.special_serenades_created}</b>`;
            $('#total_redeemed')[0].innerHTML = `<b>${data.chocolates_redeemed + data.roses_redeemed + data.serenades_redeemed + data.special_serenades_redeemed}</b>`;
        });
    }

    $('#refresh').on('click', () => {
        document.getElementById('refresh').disabled = true;
        setTimeout(() => {
            document.getElementById('refresh').disabled = false;
        }, 1000);
        refresh();
    });

    window.onload = () => {refresh();}
</script>
</html>

ticketing/templates/ticketing/stats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stats</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/stats.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icons/math.svg' %}"/>
</head>
<body>
<div id="content">
    <h1>Stats</h1>
    <table>
      <tr>
        <th>Item</th>
        <th>Amount Created</th>
        <th>Amount Redeemed</th>
      </tr>
      <tr>
        <td>Chocolate</td>
        <td id="chocolates_created"></td>
        <td id="chocolates_redeemed"></td>
      </tr>
      <tr>
        <td>Roses</td>
        <td id="roses_created"></td>
        <td id="roses_redeemed"></td>
      </tr>
      <tr>
        <td>Serenades</td>
        <td id="serenades_created"></td>
        <td id="serenades_redeemed"></td>
      </tr>
      <tr>
        <td>Special Serenades</td>
        <td id="special_serenades_created"></td>
        <td id="special_serenades_redeemed"></td>
      </tr>
       <tr>
        <td><b>Total</b></td>
        <td id="total_created"></td>
        <td id="total_redeemed"></td>
      </tr>
    </table>
    <br>
    <table style="text-align: center">
      <tr>
        <th>Grade of Recipients</th>
        <th>Number of Tickets</th>
      </tr>
      <tr>
        <td>7</td>
        <td id="grade_7"></td>
      </tr>
      <tr>
        <td>8</td>
        <td id="grade_8"></td>
      </tr>
      <tr>
        <td>9</td>
        <td id="grade_9"></td>
      </tr>
      <tr>
        <td>10</td>
        <td id="grade_10"></td>
      </tr>
      <tr>
        <td>11</td>
        <td id="grade_11"></td>
      </tr>
      <tr>
        <td>12</td>
        <td id="grade_12"></td>
      </tr>
    </table>
    <button id="refresh">Refresh</button>
    <br/><br/>
    <h2 id="graphPlaceholder">Loading graph...</h2>
    <div hidden id="graphs">
        <h2>Ticket Redemptions Over Time</h2>
        <div id="graph"></div>
        <h2>Cumulative Redemptions</h2>
        <div id="graphCumulative"></div>
    </div>
</div>
</body>
<script>
    function refresh() {
        fetch("{% url 'ticketing:api_count' %}")
        .then((response) => response.json())
        .then((data) => {
            document.getElementById('chocolates_created').innerText = data.chocolates_created;
            document.getElementById('chocolates_redeemed').innerText = data.chocolates_redeemed;
            document.getElementById('roses_created').innerText = data.roses_created;
            document.getElementById('roses_redeemed').innerText = data.roses_redeemed;
            document.getElementById('serenades_created').innerText = data.serenades_created;
            document.getElementById('serenades_redeemed').innerText = data.serenades_redeemed;
            document.getElementById('special_serenades_created').innerText = data.special_serenades_created;
            document.getElementById('special_serenades_redeemed').innerText = data.special_serenades_redeemed;
            document.getElementById('total_created').innerHTML = `<b>${data.chocolates_created + data.roses_created + data.serenades_created + data.special_serenades_created}</b>`;
            document.getElementById('total_redeemed').innerHTML = `<b>${data.chocolates_redeemed + data.roses_redeemed + data.serenades_redeemed + data.special_serenades_redeemed}</b>`;

            document.getElementById('grade_7').innerText = data.grade_7;
            document.getElementById('grade_8').innerText = data.grade_8;
            document.getElementById('grade_9').innerText = data.grade_9;
            document.getElementById('grade_10').innerText = data.grade_10;
            document.getElementById('grade_11').innerText = data.grade_11;
            document.getElementById('grade_12').innerText = data.grade_12;
        })
        .catch((error) => {
            console.error('Error:', error);
        });
    }

    document.getElementById('refresh').addEventListener('click', () => {
        document.getElementById('refresh').disabled = true;
        setTimeout(() => {
            document.getElementById('refresh').disabled = false;
        }, 1000);
        refresh();
    });

    function makeGraph(div, xData, yData) {
        const maxWidth = Math.min(document.querySelector('h1').offsetWidth, 600);
        div.style = `width: ${maxWidth}px; height: ${maxWidth * 0.66}px;`;
        Plotly.newPlot(div, [{
            x: xData,
            y: yData,
            type: 'scatter',
        }], {
            margin: {t: 20, b: 18, l: 32, r: 10},
        }, {
            modeBarButtonsToRemove: ['autoScale2d'],
            displaylogo: false,
        });
    }

    function getGraph() {
        fetch("{% url 'ticketing:api_graph' %}")
            .then((response) => response.json())
            .then((data) => {
                console.log(data);
                if (data.success === "true") {
                    makeGraph(document.getElementById('graph'), data.xData, data.yData);

                    let cumulative = 0;
                    let yDataCumulative = [];
                    for (let i = 0; i < data.yData.length; i++) {
                        cumulative += data.yData[i];
                        yDataCumulative.push(cumulative);
                    }
                    makeGraph(document.getElementById('graphCumulative'), data.xData, yDataCumulative);
                    document.getElementById('graphs').hidden = false;
                }
                document.getElementById('graphPlaceholder').hidden = true;
            })
            .catch((error) => {
               console.error('Error:', error);
            });
    }

    window.onload = () => {refresh(); getGraph();}
</script>
<script src="https://cdn.plot.ly/plotly-2.18.0.min.js"></script>
</html>

ticketing/templates/ticketing/students_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Successfully Uploaded!</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icons/upload.svg' %}"/>
</head>
<body>
    <div id="content">
        <h1>Successfully Loaded</h1>
        <p>Don't forget to reload the website!</p>
    </div>
</body>
</html>

ticketing/templates/ticketing/timetables_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Successfully Uploaded!</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icons/upload.svg' %}"/>
</head>
<body>
    <div id="content">
        <h1>Successfully Loaded</h1>
        <p>Don't forget to reload the website!</p>
    </div>
</body>
</html>